name: Update Node Dependencies
branding:
  icon: package
  color: green
description: Updates Node dependencies and creates a pull request with the changes.
inputs:
  bump-version:
    description: If set, bumps the package version based on value (e.g. patch)
    default: ''
  git-user-email:
    description: Git user.email to use for the commit.
    default: 41898282+github-actions[bot]@users.noreply.github.com
  git-user-name:
    description: Git user.name to use for the commit.
    default: github-actions[bot]
  pre-commit-script:
    description: A command to run before committing the dependency changes (e.g. npm run build)
  package-manager:
    description: Set to 'yarn' to use yarn. Defaults to npm.
    default: npm
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.git-user-name }}
    - ${{ inputs.git-user-email }}
    - ${{ inputs.package-manager }}
    - ${{ inputs.bump-version }}
    - ${{ inputs.pre-commit-script }}
